/**
 * `i18n codegen` command — generate TypeScript types from translation keys.
 *
 * @module commands/codegen
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { Command } from 'commander';
import type { TranslationMap } from '@i18n-platform/core';
import { loadProjectConfig } from '../config.js';
import { ApiClient } from '../api-client.js';
import { logger } from '../utils/logger.js';

/**
 * Shape of a translation bundle returned by the API.
 * @internal
 */
interface TranslationBundle {
  locale: string;
  namespace: string;
  translations: TranslationMap;
}

/**
 * Converts a string to PascalCase for use as a TypeScript type name.
 *
 * @param value - Input string (e.g., `"common"`, `"auth-errors"`)
 * @returns PascalCase identifier (e.g., `"Common"`, `"AuthErrors"`)
 * @internal
 */
function toPascalCase(value: string): string {
  return value
    .replace(/[-_\s]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (c: string) => c.toUpperCase());
}

/**
 * Generates a TypeScript union type of string literals for an array of keys.
 *
 * @param typeName - Name of the exported type
 * @param keys     - Translation key strings
 * @returns TypeScript source fragment
 * @internal
 */
function buildKeyUnionType(typeName: string, keys: string[]): string {
  if (keys.length === 0) {
    return `export type ${typeName} = never;\n`;
  }
  const union = keys.map((k) => `  | '${k}'`).join('\n');
  return `export type ${typeName} =\n${union};\n`;
}

/**
 * Registers the `codegen` command with the Commander program.
 *
 * Fetches translation keys from the platform for the source locale, then
 * generates a TypeScript source file exporting:
 *
 * - A union type per namespace (e.g., `CommonKeys`, `AuthKeys`)
 * - An `AllTranslationKeys` master union type
 * - A `Namespaces` union type
 * - A `Locales` union type derived from `config.supportedLocales`
 *
 * Options:
 * - `--config <path>`  — path to an explicit config file
 * - `--out <path>`     — output file path (default: `src/i18n.generated.ts`)
 *
 * @param program - The root Commander {@link Command} instance
 */
export function registerCodegenCommand(program: Command): void {
  program
    .command('codegen')
    .description('Generate TypeScript types from translation keys')
    .option('-c, --config <path>', 'Path to i18n config file')
    .option(
      '--out <path>',
      'Output file path',
      'src/i18n.generated.ts',
    )
    .action(async (options: { config?: string; out: string }) => {
      let config;
      try {
        config = await loadProjectConfig(options.config);
      } catch (err) {
        logger.error((err as Error).message);
        process.exit(1);
      }

      const spinner = logger.spinner('Fetching translation keys…');
      const client = new ApiClient(config.apiUrl, config.apiKey);

      try {
        const bundles = await client.get<TranslationBundle[]>(
          `/projects/${config.projectId}/translations/${config.defaultLocale}`,
        );

        spinner.text = 'Generating TypeScript types…';

        // Build per-namespace key maps
        const namespaceKeys = new Map<string, string[]>();
        for (const bundle of bundles) {
          const keys = Object.keys(bundle.translations);
          namespaceKeys.set(bundle.namespace, keys);
        }

        const lines: string[] = [
          '/**',
          ' * Auto-generated by `i18n codegen`.',
          ' * Do not edit this file manually — run `i18n codegen` to regenerate.',
          ' *',
          ` * Generated: ${new Date().toISOString()}`,
          ' */',
          '',
        ];

        const nsNames: string[] = [];

        for (const [ns, keys] of namespaceKeys) {
          const typeName = `${toPascalCase(ns)}Keys`;
          nsNames.push(ns);
          lines.push(`/** Translation keys in the "${ns}" namespace. */`);
          lines.push(buildKeyUnionType(typeName, keys));
        }

        // Master union
        if (nsNames.length > 0) {
          const masterUnion = nsNames
            .map((ns) => `${toPascalCase(ns)}Keys`)
            .join(' | ');
          lines.push('/** Union of all translation keys across all namespaces. */');
          lines.push(`export type AllTranslationKeys = ${masterUnion};\n`);
        } else {
          lines.push('export type AllTranslationKeys = never;\n');
        }

        // Namespaces union
        const nsLiterals = nsNames.map((ns) => `'${ns}'`).join(' | ');
        lines.push('/** Union of all namespace names. */');
        lines.push(
          `export type Namespaces = ${nsLiterals.length > 0 ? nsLiterals : 'never'};\n`,
        );

        // Locales union
        const localeLiterals = config.supportedLocales
          .map((l) => `'${l}'`)
          .join(' | ');
        lines.push('/** Union of all supported locale codes. */');
        lines.push(`export type Locales = ${localeLiterals};\n`);

        const outPath = join(process.cwd(), options.out);
        await mkdir(dirname(outPath), { recursive: true });
        await writeFile(outPath, lines.join('\n'), 'utf-8');

        spinner.succeed(`Generated TypeScript types → ${options.out}`);
      } catch (err) {
        spinner.fail('Codegen failed');
        logger.error((err as Error).message);
        process.exit(1);
      }
    });
}
